name: Snyk Actions and CLI
# Prerequisites:
# - Set a SNYK_TOKEN under env secrets in an env called "Snyk"
# - If you are not running the scan on your default org in Snyk, set the org id in a secret called SNYK_ORG in the same env as above (env called "Snyk") and add an additional --org=${{ secrets.SNYK_ORG }} parameter in all the test commands 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  # SCA
  snyk-test:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('package.json') }}
          path: node_modules           
        
      - name: Get Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.10.0
      - name: Install dependencies
        run: npm install
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: Monitor dependencies for security issues with Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        continue-on-error: true
  # SAST
  snyk-test-code:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-container:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boosef-juiceshop:latest
    - name: Scan and Monitor Docker Image vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: boosef-juiceshop:latest
        command: monitor
      continue-on-error: true

  snyk-iac:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Snyk scan IAC files
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --report
