name: Snyk Full Platform (CLI)

# Prerequisites:
# - Set a SNYK_TOKEN under env secrets in an env called "Snyk"
# - If you are not running the scan on your default org in Snyk, set the org id in a secret called SNYK_ORG in the same env as above (env called "Snyk") and add an additional --org=${{ secrets.SNYK_ORG }} parameter in all the test commands 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  

jobs:
  snyk-os:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: Install dependencies
        run: npm install
      - name: Authenticate 
        run: snyk auth ${{ secrets.SNYK_TOKEN }}        
      - name: Snyk test
        run: snyk test --all-projects
      - name: Snyk monitor
        run: snyk monitor
        continue-on-error: true
  snyk-code:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: Configure and run Snyk Code Scan
        run: | 
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk code test
        continue-on-error: true
  snyk-container:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boosef-juiceshop:latest
    - name: Install Snyk CLI
      run: |
        wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/
    - name: Scan and Monitor Docker Vulnerabilities
      run: |   
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk container test boosef-juiceshop:latest --file=Dockerfile
        snyk container monitor boosef-juiceshop:latest --file=Dockerfile
      continue-on-error: true

  snyk-iac:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Snyk CLI
      run: |
        wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/
    - name: Run and monitor Snyk to check configuration files for security issues
      run: |   
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk iac test --report
      continue-on-error: true
