name: Snyk - CLI
# Prerequisites:
# - Set a SNYK_TOKEN under env secrets in an env called "Snyk"
# - If you are not running the scan on your default org in Snyk, set the org id in a secret called SNYK_ORG in the same env as above (env called "Snyk") and add an additional --org=${{ secrets.SNYK_ORG }} parameter in all the test commands 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:

  # SCA
  snyk-test:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: print
        run: ls 
      - name: Get Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.10.0
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('package.json') }}
          path: node_modules          
      - name: Install dependencies
        run: npm install
      - name: Authenticate 
        run: snyk auth ${{ secrets.SNYK_TOKEN }}       
      - name: print
        run: ls    
      - name: Snyk test
        run: snyk test --all-projects
        continue-on-error: true
      - name: Snyk monitor
        run: snyk monitor
        continue-on-error: true

  # SAST 
  snyk-test-code:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      - name: Authenticate 
        run: snyk auth ${{ secrets.SNYK_TOKEN }}      
      - name: Run Snyk Code Scan
        run: snyk code test
        continue-on-error: true

  # Container 
  snyk-test-container:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boosef-juiceshop:latest
    - name: Install Snyk CLI
      run: |
        wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/
    - name: Authenticate 
      run: snyk auth ${{ secrets.SNYK_TOKEN }}  
    - name: Scan container
      run:  snyk container test boosef-juiceshop:latest --file=Dockerfile
      continue-on-error: true
    - name: Monitor Docker Vulnerabilities
      run: snyk container monitor boosef-juiceshop:latest --file=Dockerfile
      continue-on-error: true

  # IAC
  snyk-test-iac:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Snyk CLI
      run: |
        wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/        
    - name: Authenticate 
      run: snyk auth ${{ secrets.SNYK_TOKEN }}  
    - name: Run snyk IAC
      run: snyk iac test --report
      continue-on-error: true
